// NewEvent Plug-in
// Initial code generated by Softimage SDK Wizard
// Executed Fri Apr 29 00:05:10 UTC+0200 2011 by StefanKubicek


function XSILoadPlugin( in_reg )
{
	in_reg.Author = "StefanKubicek";
	in_reg.Name = "QMenuRememberRecentNode";
	in_reg.Major = 1;
	in_reg.Minor = 0;

	in_reg.RegisterEvent("QMenuRememberRecentNodeEvent", siOnBeginCommand);
	in_reg.RegisterCommand( "QMenuGetRecentNode" , "QMenuGetRecentNode" );
	
	//RegistrationInsertionPoint - do not remove this line

	return true;
}

function XSIUnloadPlugin( in_reg )
{
	var strPluginName;
	strPluginName = in_reg.Name;
	Application.LogMessage(strPluginName + " has been unloaded.",siVerbose);
	return true;
}

// Callback for the QMenuRecordMRUNodes event.
function QMenuRememberRecentNodeEvent_OnEvent( in_ctxt )
{
	var LastCmd = in_ctxt.GetAttribute("Command");
	var ScriptingName = LastCmd.ScriptingName;
	var strLastNodeCommandAndArgument = "";
		if (ScriptingName == "AddICENode")
		{
			strLastNodeCommandAndArgument = (ScriptingName + ";" + LastCmd.Arguments.Item(0).Value);
			Application.Plugins("QMenuRememberRecentNode").UserData = strLastNodeCommandAndArgument;
			storeLastNodeCommandAndPresetName(strLastNodeCommandAndArgument);
		}
		else if (ScriptingName == "AddICECompoundNode")
		{
			strLastNodeCommandAndArgument = (ScriptingName + ";" + LastCmd.Arguments.Item(0).Value);
			Application.Plugins("QMenuRememberRecentNode").UserData = strLastNodeCommandAndArgument;
			storeLastNodeCommandAndPresetName(strLastNodeCommandAndArgument);
		}
		
		else if (ScriptingName == "CreateShaderFromProgID")
		{
			strLastNodeCommandAndArgument = (ScriptingName + ";" + LastCmd.Arguments.Item(0).Value);
			Application.Plugins("QMenuRememberRecentNode").UserData = strLastNodeCommandAndArgument;
			storeLastNodeCommandAndPresetName(strLastNodeCommandAndArgument);
		}
		

// 	This event can be aborted by returning true or false if you don't want to abort.
	return false;
}


function QMenuGetRecentNode_Execute()
{
	//thisPlugin = Application.Plugins("QMenuRememberRecentNode");
	return Application.Plugins("QMenuRememberRecentNode").UserData;
}

function storeLastNodeCommandAndPresetName(strCmdAndPresetName)
{
	if (strCmdAndPresetName != "")
		{
			oQMenuGlobals = Application.Plugins("QMenuConfigurator").UserData;
			oQMenuContext = oQMenuGlobals["globalQMenu_ContextObject"];
			oQMenuContext.storeLastICENode(strCmdAndPresetName);
		}
}

