// SelectOperatorInputsPlugin
// Initial code generated by Softimage SDK Wizard
// Executed Thu Feb 18 09:37:10 UTC+0100 2010 by Eugen
// 
// Selects all Inputs of a selected Operator.
// Useful e.g. to select all Curves connected to a CurvesToMesh Op.
//
// Usage: select an Operator, run script.

function XSILoadPlugin( in_reg )
{
	in_reg.Author = "Eugen";
	in_reg.Name = "SelectOperatorInputsPlugin";
	in_reg.Major = 1;
	in_reg.Minor = 0;

	in_reg.RegisterCommand("SelectOperatorInputs","SelectOperatorInputs");
	//RegistrationInsertionPoint - do not remove this line

	return true;
}

function XSIUnloadPlugin( in_reg )
{
	var strPluginName;
	strPluginName = in_reg.Name;
	Application.LogMessage(strPluginName + " has been unloaded.",siVerbose);
	return true;
}

function SelectOperatorInputs_Init( in_ctxt )
{
	var oCmd;
	oCmd = in_ctxt.Source;
	oCmd.Description = "";
	oCmd.ReturnValue = true;
	
	oArgs = oCmd.Arguments;
	oArgs.AddWithHandler("Arg0","Collection");

	return true;
}

function SelectOperatorInputs_Execute( Arg0 )
{

	Application.LogMessage("SelectOperatorInputs_Execute called",siVerbose);
	//
	var oCollection = new ActiveXObject("XSI.Collection");
	for(var j = 0; j < Arg0.Count; j++)
	{
		var oOp = Arg0(j);	// loop through all selected Ops
		//LogMessage(oOp.Type);
		//LogMessage(ClassName(oOp));	// Operator

		if(ClassName(oOp) == "Operator")
		{
			var oInputPorts = oOp.InputPorts;	// InputPortCollection
			if(oInputPorts)
			{
				for(var i = 0; i < oInputPorts.Count; i++)
				{
					var oTarget = oInputPorts(i).Target2;
					//LogMessage("type: " + oTarget.Type);
					//LogMessage("classname: " + ClassName(oTarget));
					if(ClassName(oTarget) == "Primitive") oCollection.Add(oTarget.parent);
				}
			}
		}
	}
	
	Application.Selection.Clear();
	for(var i = 0; i < oCollection.Count; i++)
	{
		Application.Selection.Add(oCollection.Item(i));
	}

	// 
	return true;
}

